# NOTICE: copy and rename this file to config.yaml
# NOTICE: some cofig need to complete


# nodes ony need to set this item
# etcd-addr: 172.16.232.8:2379

# etcd server need to complete these items
server:
  jwt-secret: MTAxNTkwMTg1Mw==
  version: "1.0"
  name: runFzu

snowflake:
  worker-id: 0
  datancenter-id: 0

mysql:
  addr: 127.0.0.1:3306
  database: garage
  username: root
  password: root
  charset: utf8mb4

qss:
  access-key: bvNjY2qeTRz1rNw9NfdEEFUV9yBRlDSfwoMtAWHB
  serect-key: pcovzI0wcNQO_DUTVv97PpkrWqLxz7gmSJK0EluR
  qiniu-server: s49neujkg.hn-bkt.clouddn.com/
  bucket: suijiapp
  
# you need to complete this config to use video service
# oss:
#   endpoint:
#   accessKey-id:
#   accessKey-secret:
#   bucketname:
#   main-directory: tiktok

# uss:
#   service: "fzuhelper-assets"
#   user: "spf"
#   pass: "7lRQ6j2HZCyI86bUtsAnvJ4UfEs3eXh7"
#   domainname: "http://fzuhelper-assets.test.upcdn.net"
#   path: "/pictures/"

# elasticsearch:
#   addr: 127.0.0.1:9200
#   host: 127.0.0.1

# etcd:
#   addr: 127.0.0.1:2379

# rabbitmq:
#   addr: 127.0.0.1:5672
#   username: tiktok
#   password: tiktok

# redis:
#   addr: 127.0.0.1:6379
#   password: tiktok

# jaeger:
#   addr: 127.0.0.1:6831

# if you deploy in different machines, remember to modify IP.
# services:
#   api:
#     name: api
#     load-balance: false
#     addr:
#       - 127.0.0.1:10001