// Code generated by hertz generator.

package base

import (
	"context"

	base "github.com/XZ0730/hertz-scaffold/biz/model/base"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
// @router /ping [GET]
func Ping(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.BaseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.BaseResponse)

	c.JSON(consts.StatusOK, resp)
}

// Register .
// @router /auth/register/pwd [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.BaseResponse)

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /auth/login/pwd [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.LoginResponse)

	c.JSON(consts.StatusOK, resp)
}
