// Code generated by hertz generator.

package manager

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _managerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgarageparkspaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getparkrecordlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cntvolumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvehicleauditMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditvehicleMw() []app.HandlerFunc {
	// your code...
	return nil
}
