// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	base "github.com/XZ0730/hertz-scaffold/biz/router/base"
	manager "github.com/XZ0730/hertz-scaffold/biz/router/manager"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	manager.Register(r)

	base.Register(r)

}
